baseURL = "https://tzuhan2575.github.io/"
publishDir = "public"
languageCode = 'en-us'
title = 'TzuHan Blog'
theme = 'PaperMod'
[params]
  ShowFullTextinHome = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowToc = false
  TocOpen = false
  [params.homeInfoParams]
    Title = "å—¨ï¼Œæˆ‘æ˜¯ TzuHan ğŸ‘‹"
    Content = "ä¸€å€‹ç†±æ„›TWICEã€å¯«ä½œèˆ‡å­¸ç¿’æ–°çŸ¥çš„è³‡å·¥ç ”ç©¶ç”Ÿã€‚é€™è£¡æ˜¯æˆ‘çš„æ•¸ä½ç­†è¨˜åˆ†äº«å€ï¼Œæ­¡è¿éš¨æ„é€›é€›ï¼"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true